name: Time it!

on: [push]

jobs:
  # build-rust:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Install Rust
  #     uses: actions-rs/toolchain@v1
  #     with:
  #         toolchain: nightly
  #   - name: Cargo cache
  #     uses: Swatinem/rust-cache@v1
  #   - name: Install Rust dependencies
  #     run: |
  #       cargo install --git https://github.com/simoncozens/rust-font-tools fonticulus
  #       cargo install --git https://github.com/simoncozens/rust-font-tools ufo-cu2qu
  #       cargo install --git https://github.com/simoncozens/rust-font-tools ufo-decompose
  #   - name: Archive built rust utilities
  #     uses: actions/upload-artifact@v2
  #     with:
  #       name: cargo-bin
  #       path: ~/.cargo/bin/

  build:
    # needs: build-rust
    name: ${{ matrix.font.name }} - ${{ matrix.builder.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        font:
          - name: "Noto Sans"
            short: notosans
            repo: "notofonts/latin-greek-cyrillic"
            root: "sources/NotoSans-MM.glyphs"
          - name: "Noto Sans Myanmar"
            short: nsmyanmar
            repo: "notofonts/myanmar"
            root: "sources/NotoSansMyanmar.glyphs"
          - name: "Roboto Serif"
            short: roboto
            repo: "googlefonts/roboto-serif"
            root: "sources/RobotoSerif.designspace"
        builder:
          - name: "Fontmake thin"
            short: fontmakethin
            command: "fontmake -o variable -- "
          - name: "Fontninja thin"
            short: fontninjathin
            command: "fontninja -o variable -- "
          # - name: "Fontninja Rust"
          #   command: "fontninja -o variable --rust -- "
    outputs:
      notosans-fontmakethin: ${{ steps.report.outputs.notosans-fontmakethin }}
      notosans-fontninjathin: ${{ steps.report.outputs.notosans-fontninjathin }}
      nsmyanmar-fontmakethin: ${{ steps.report.outputs.nsmyanmar-fontmakethin }}
      nsmyanmar-fontninjathin: ${{ steps.report.outputs.nsmyanmar-fontninjathin }}
      roboto-fontmakethin: ${{ steps.report.outputs.roboto-fontmakethin }}
      roboto-fontninjathin: ${{ steps.report.outputs.roboto-fontninjathin }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v1
      with:
        python-version: "3.10"
    - name: Install Python dependencies
      run: pip install -r requirements.txt
    # - name: Install Rust
    #   uses: actions-rs/toolchain@v1
    #   with:
    #       toolchain: nightly
    # - name: Download Rust utils
    #   uses: actions/download-artifact@v3
    #   with:
    #     name: cargo-bin
    #     path: ~/.cargo/bin
    - name: Clone
      uses: actions/checkout@v2
      with:
        repository: ${{ matrix.font.repo }}
        path: font
    - name: Build
      run: /usr/bin/time -f "\t%E real,\t%U user,\t%S sys" -o stats ${{ matrix.builder.command }} font/${{matrix.font.root}}
    - name: Report
      id: report
      run: |
        result=`cat stats`
        echo '::set-output name=${{ matrix.font.short }}-${{matrix.builder.short}}::$result'

  report:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - env:
          NEEDS: ${{ toJSON(needs) }}
        run: echo "$NEEDS"
